---
  - name: elk server
    hosts: elk
    become: true
    tasks:

    - ansible.posix.sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present

    - name: Install docker.io (state=present is optional)
      apt:
        name: docker.io
        update_cache: yes
        state: present

    - name: Install python3-pip (state=present is optional)
      apt:
        name: python3-pip
        state: present

    - name: Install docker python
      pip:
        name: docker
        state: present

    - name: Create elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart: yes
        ports:
          - "5601:5601"
          - "9200:9200"
          - "5044:5044"

    - name: Make sure docker is running
      ansible.builtin.systemd:
        state: started
        name: docker